In [5]:
import cv2

In [3]:
path = "image.jpg"
img = cv2.imread(path)
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[110  77  58]
  [107  71  53]
  [ 87  48  33]
  ...
  [ 46  30  18]
  [ 51  39  29]
  [ 31  20  12]]

 [[132  90  71]
  [123  83  64]
  [ 92  54  36]
  ...
  [ 42  25  16]
  [ 53  40  32]
  [ 28  18  11]]

 [[139  85  62]
  [144  97  75]
  [101  64  44]
  ...
  [ 51  32  24]
  [ 46  32  26]
  [ 19  12   9]]]


In [9]:
cv2.imshow("i", img)

In [10]:
import cv2 
path = "image.jpg"
img = cv2.imread(path)
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[110  77  58]
  [107  71  53]
  [ 87  48  33]
  ...
  [ 46  30  18]
  [ 51  39  29]
  [ 31  20  12]]

 [[132  90  71]
  [123  83  64]
  [ 92  54  36]
  ...
  [ 42  25  16]
  [ 53  40  32]
  [ 28  18  11]]

 [[139  85  62]
  [144  97  75]
  [101  64  44]
  ...
  [ 51  32  24]
  [ 46  32  26]
  [ 19  12   9]]]


In [11]:
import cv2 
path = "image.jpg"
img = cv2.imread(path, 0)
print(img)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [ 75  70  48 ...  28  37  19]
 [ 89  82  53 ...  24  39  17]
 [ 84  96  62 ...  32  32  12]]


In [ ]:
cv2.imshow("i", img)

: 

In [3]:
import matplotlib.pyplot as plt
import cv2 


In [8]:
path = "image.jpg"
img = cv2.imread(path, -1)

In [13]:
cv2.imshow("i",img)

In [10]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[110  77  58]
  [107  71  53]
  [ 87  48  33]
  ...
  [ 46  30  18]
  [ 51  39  29]
  [ 31  20  12]]

 [[132  90  71]
  [123  83  64]
  [ 92  54  36]
  ...
  [ 42  25  16]
  [ 53  40  32]
  [ 28  18  11]]

 [[139  85  62]
  [144  97  75]
  [101  64  44]
  ...
  [ 51  32  24]
  [ 46  32  26]
  [ 19  12   9]]]


In [11]:
print(img.shape)

(225, 225, 3)


In [14]:
import cv2  
path = "image.jpg"
img = cv2.imread(path, 0)
print(img)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [ 75  70  48 ...  28  37  19]
 [ 89  82  53 ...  24  39  17]
 [ 84  96  62 ...  32  32  12]]


In [15]:
print(img.shape)

(225, 225)


In [7]:
path = "cameraman.jpg"
img = cv2.imread(path, -1)

In [17]:
print(img)
print(img.shape)

[[[155 155 155]
  [156 156 156]
  [157 157 157]
  ...
  [154 154 154]
  [153 153 153]
  [153 153 153]]

 [[155 155 155]
  [156 156 156]
  [157 157 157]
  ...
  [154 154 154]
  [153 153 153]
  [153 153 153]]

 [[155 155 155]
  [156 156 156]
  [157 157 157]
  ...
  [153 153 153]
  [152 152 152]
  [152 152 152]]

 ...

 [[135 135 135]
  [133 133 133]
  [130 130 130]
  ...
  [119 119 119]
  [123 123 123]
  [123 123 123]]

 [[130 130 130]
  [130 130 130]
  [130 130 130]
  ...
  [111 111 111]
  [114 114 114]
  [114 114 114]]

 [[127 127 127]
  [128 128 128]
  [129 129 129]
  ...
  [101 101 101]
  [104 104 104]
  [104 104 104]]]
(148, 192, 3)


In [18]:
cv2.imshow("i",img)

In [8]:
# Perform digital negative image
img = cv2.imread(path, 0)
m,n = img.shape
L = img.max()
negative = L - img
# cv2.imshow("IMAGE_NEGATIVR", negative)

In [11]:
#THRESHOLDING OPERATION
# IF r < T THEN S = 0
# IF r > T THEN S = 255
import numpy as np
T = input("Enter the Threshold Value: ")
T = int(T)
img_thres = np.zeros((m,n), dtype =np.uint8)

for i in range(m):
    for j in range(n):
        if img[i,j] > T:
            img_thres[i,j] = 255
        else:
            img_thres[i,j] = 0

cv2.imshow("cameraman.jpg", img_thres)
cv2.waitKey(10000)
cv2.destroyAllWindows()


In [1]:
# Grey Level Slicing
import cv2
import numpy as np
path = "cameraman.jpg"
img = cv2.imread(path, 0)
m,n = img.shape
T1 = input("Enter the lower Threshold Value: ")
T2 = input("Enter the Upper Threshold Value: ")
T1 = int(T1)
T2 = int(T2)
img_new = np.zeros((m,n), dtype = np.uint8)
for i in range(m):
    for j in range(n):
        if T1 < img[i,j] < T2:
            img_new[i,j] = 255
        else:
            img_new[i,j] = img[i,j]
cv2.imshow("cameraman.jpg", img_new)
cv2.waitKey(10000)
cv2.destroyAllWindows()


2024-07-26 14:39:44.056 Python[72146:9071413] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.


In [1]:
# Power-Law (Gamma) Transformation
import cv2
import numpy as np
path = "cameraman.jpg"
img = cv2.imread(path, 0)
for gamma in [0.1, 0.5, 1.2, 2.2]:
    gamma_corrected = np.array(255*(img/255)**gamma, dtype = np.uint8)
    cv2.imshow("cameraman.jpg", gamma_corrected)
    cv2.waitKey(2000)
cv2.destroyAllWindows()


2024-07-26 14:50:06.724 Python[72360:9079365] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.


: 